### ISSUE TITLE
未找到此处方(请检查地址有效性)

### ISSUE THREAD

**Issue by lifansama** [hexian000/rxs-easycoll#1]
![Screenshot_20201210-230635](https://user-images.githubusercontent.com/17267120/101789607-7744b480-3b3c-11eb-8925-36ca99362905.jpg)

**Comment by hexian000** [comment]
https://github.com/hexian000/rxs-easycoll/commit/01997bd6857cd0aaf617139e04dcbcd8faf6ae76
已经修复，请重试
